In [9]:
import tensorflow as tf 
import numpy as np

In [10]:
# 是否在Eager模式下：各种计算可以立即出结果！
tf.executing_eagerly()

True

# 说明

下面用一系列计算，来展示张量的各种操作；并体会Eager模式下，每一步计算都可立即出结果！

tf中的tensor数据类型 v.s. numpy中的ndarray数据类型：★
- tensor就是ndarray，就当成**高维数组**看待即可！—— 因为Tensorflow最初就是照着Numpy改写的，但又想替代Numpy，故把核心数据类型换了个名字！
- tensor数据类型具有的3个属性：结构、尺寸(shape)、元素的数据类型 —— 也和Numpy很像！
- **最大区别**：tensor内部数值不能修改！！！ndarray可以修改！—— 所以所有的张量，都可以当作是“**常量**”！★★
- 小区别：tensor既可以内存中存，又可在gpu显存中存。

In [11]:
# 一个numpy的2维数组：
x = np.array( [[2,3], [4,5]] )
print(x)

[[2 3]
 [4 5]]


In [12]:
# 用一个tf的运算：
m = tf.matmul(x, x)
print(m)  # Eager模式，可以理解打印计算后的结果！

tf.Tensor(
[[16 21]
 [28 37]], shape=(2, 2), dtype=int32)


In [ ]:
# ndarray可以修改数组里的数值：

In [15]:
x[0][1] = 199
x

array([[  2, 199],
       [  4,   5]])

In [ ]:
m[0][1] = 199  # tensor不能修改，这里会报错！

# 一些关于张量的操作

下面介绍一些常见关于张量的操作：
1. 张量（张量常量）的创建：tf.constant( [[2,3],[4,5]] ) —— 写法和np.array()一样！
2. 张量转ndarray数据类型：xxx.numpy()
3. ndarray、python数据类型转tensor：tf.convert_to_tensor()
4. 张量加法运算：tf.add(x,y) —— y可以是一个数值，也可以是一个同shape的张量
5. 张量乘法运算：tf.multiply(x,y) —— 同上
6. python运算符和数据、numpy运算符和数据、tensor运算符和数据，3者间无缝进行！！！★★
7. 直接使用宿主语言python控制流等“**结构化、功能化**”语句

In [18]:
# 1. 创建一个张量（张量常量）：
a = tf.constant( [[2,3],[4,5]] )
print(a)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [19]:
# 2. 把张量转为对应的ndarray：
a1 = a.numpy()
type(a1)

numpy.ndarray

In [28]:
# 3. python数据转tensor
n1 = np.array( [[1,2],[3,4]] )
n2 = 10

tn1 = tf.convert_to_tensor(n1)
tn2 = tf.convert_to_tensor(n2)
print(tn1), print(tn2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


(None, None)

In [23]:
# 4. 张量加法：
b = tf.add(a,a+1)
print(b)

tf.Tensor(
[[ 5  7]
 [ 9 11]], shape=(2, 2), dtype=int32)


In [24]:
# 5. 张量乘法：
c = tf.multiply(a,b)
print(c)

tf.Tensor(
[[10 21]
 [36 55]], shape=(2, 2), dtype=int32)


In [32]:
# 6. python、numpy、tensor无缝协作：
d1 = 2
d2 = np.array( [[2,3],[4,5]] )
t1 = tf.convert_to_tensor(d1)
t2 = tf.convert_to_tensor(d2)

result1 = tf.add(d2,t2)  # 放在一起算
print(result1)

result2 = float(t1)  # 用python运算符直接作用于tensor常量上
print(result2), print( type(result2) )

tf.Tensor(
[[ 4  6]
 [ 8 10]], shape=(2, 2), dtype=int32)
2.0
<class 'float'>


(None, None)